### ISSUE TITLE
给一个详细的通过IDEA搭建工程的文档吧

### ISSUE THREAD

**Issue by hanyou** [ogcs/Okra#10]
我使用导入方式创建了工程，但core始终无法编译、打包，能给一份文档吗？

**Comment by TinyZzh** [comment]
Maven目前只用于解决Okra的依赖库问题。没有使用Maven打包和发布。
**不推荐**自己编译工程，因为目前pom还没有完善好。
假如要使用的话推荐使用发布的版本，连接[最新版本](https://github.com/ogcs/Okra/releases/tag/v1.0.1)
导入到工程就可以使用了

**Comment by TinyZzh** [comment]
关闭问题。还有使用的疑问，欢迎继续提问
