### ISSUE TITLE
多种连接方式

### ISSUE THREAD

**Issue by maynezhou** [ogcs/Okra#32]
服务器需要同时具备http/tcp 两种连接方式，如何实现呢？

**Comment by TinyZzh** [comment]
方案一（推荐）：启动两个TcpProcotolServer一个处理Http协议，一个处理Tcp协议。
方案二：共用一个Server，在链路中根据请求的报文头区别Http请求亦或者Tcp请求。完全不推荐。
可以参考netty.io学习使用netty。不属于issue
