### ISSUE TITLE
请问如何整合Spring Boot

### ISSUE THREAD

**Issue by java-war** [ogcs/Okra#35]
使用Spring boot整合无法启动TCPServer

`@SpringBootApplication
public class ServerApplication implements CommandLineRunner {

    @Autowired
    TcpServer tcpServer;

    public static void main(String[] args) {
        SpringApplication.run(ServerApplication.class, args);
    }

    @Override
    public void run(String... strings) throws Exception {
        tcpServer.start();
    }
}
`

**Comment by TinyZzh** [comment]
请仔细检查spring框架配置文件是否正确加载。bean初始化等是否正确。详细问题请移步到spring boot社区提问。
不属于okra的bug。关闭问题
