### ISSUE TITLE
Disruptor出现多个线程的问题

### ISSUE THREAD

**Issue by veione** [ogcs/Okra#39]
在src/main/java/org/ogcs/netty/handler/DisruptorAdapterBy41xHandler.java源码中：
private static final ThreadLocal<Disruptor<ConcurrentEvent>> THREAD_LOCAL = new ThreadLocal<Disruptor<ConcurrentEvent>>() {
        @Override
        protected Disruptor<ConcurrentEvent> initialValue() {
            Disruptor<ConcurrentEvent> disruptor = new Disruptor<>(
                    ConcurrentEventFactory.DEFAULT, DEFAULT_RING_BUFFER_SIZE, CACHED_THREAD_POOL, ProducerType.SINGLE, new BlockingWaitStrategy());
            disruptor.handleEventsWith(new ConcurrentHandler());
//            disruptor.handleExceptionsWith();
            disruptor.start();
            return disruptor;
        }
    };
这一段代码中，因为每个WorkerGroup线程访问都会创建一个Disruptor，所以会造成大量的线程不释放的问题，这个问题会伴随着客户端的增加而增加，所以在线求解。。。

**Comment by TinyZzh** [comment]
有很多种方案，
1. private static final ExecutorService CACHED_THREAD_POOL = Executors.newCachedThreadPool(); 线程池修改为固定线程数量
jdk8推荐Executors.newWorkStealingPool(10);。否则推荐newFixedThreadPool(10)

2. 
handleEventsWith(new ConcurrentHandler());修改为handleEventsWithWorkerPool
使用Disruptor内置的单生产者多消费者。 内部有锁

3. 线程逻辑异常尽可能处理一下. 使用handleExceptionsWith。即时是空的没有异常处理逻辑也比较好

**Comment by TinyZzh** [comment]
每一个Netty的work线程会对应一个Disrupotor，实现单生产者模式，避免netty的多线程竞争。  内部逻辑线程是使用Executors创建出来的线程池。 

将如不使用ThreadLocal的话，需要把Disruptor的ProducerType.SINGLE修改为ProducerType.MULTI。 有锁管理多线程竞争

**Comment by TinyZzh** [comment]
补充一个回答。 CachedThread线程池，不释放线程的问题。默认1分钟没有任何逻辑执行之后，线程池才会回收并关闭线程。

**Comment by veione** [comment]
嗯嗯，谢谢解答，我重构一下代码。
