### ISSUE TITLE
仅支持protobuf数据传输格式？

### ISSUE THREAD

**Issue by yinwhm12** [ogcs/Okra#41]
我的项目不怎么需要protobuf数据传输，主要是项目不怎么大；比较小，作者，能有考虑这点？

**Comment by TinyZzh** [comment]
项目只是提供一个范例。序列化和反序列化，你可以根据自己的需求定制。pb反而是一种麻烦的解决方式。项目小可以靠json等简单的

2018-01-02 23:46 GMT+08:00 yinwhm12 <notifications@github.com>:
