### ISSUE TITLE
volatile的使用方法

### ISSUE THREAD

**Issue by wsgzxl** [ogcs/Okra#42]
private volatile Channel channel;    
private volatile Connector connector;

请问这个volatile是什么意思？
是为了并发的时候，这些channel或者connector会改变吗？

**Comment by TinyZzh** [comment]
是的。有可能用户重登录，或其他情况，会导致channel和connector变化。

**Comment by wsgzxl** [comment]
这涉及到多线程访问，才需要用volatile吧？
