### ISSUE TITLE
这个是不是大部分地方都需要自己写代码保证并发安全，比如玩家数据会有不同线程去修改和读取

### ISSUE THREAD

**Issue by JNUMrC** [ogcs/Okra#44]
这个是不是大部分地方都需要自己写代码保证并发安全，比如玩家数据会有不同线程去修改和读取
感觉这样写业务逻辑的时候难度会增加呢

**Comment by TinyZzh** [comment]
是的，业务层需要保障并发安全

**Comment by JNUMrC** [comment]
明白了，谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ogcs/Okra"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 晚上10:11
收件人:&nbsp;"ogcs/Okra"<Okra@noreply.github.com&gt;;
抄送:&nbsp;"切克闹"<1076878143@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ogcs/Okra] 这个是不是大部分地方都需要自己写代码保证并发安全，比如玩家数据会有不同线程去修改和读取 (#44)





 
是的，业务层需要保障并发安全
