### ISSUE TITLE
增加demo工程中对配置表的支持

### ISSUE THREAD

**Issue by TinyZzh** [ogcs/Okra#7]
增加对配置表的支持
游戏服务器通常需要配置一些配置表内容。
一般就以下两种方式：
1. **服务器本地文件**。使用例如：.csv  .txt等格式的文件保存。当服务器启动时或需要热更新时，加载文件并更新到服务器数据中。
2. **数据库保存**。使用各种类型的数据库保存相对应的配置表。

作者这里推荐的方式是**第一种**。本地文件相对来说对策划更友好（不需要额外掌握数据库相关东西）。

**Comment by TinyZzh** [comment]
指派给@TinyZzh

**Comment by justein** [comment]
感觉还是需要完善下 Readme 文档，demo和example中的例子还不太详细

**Comment by TinyZzh** [comment]
[#17 ] 在查看DEMO的进度

**Comment by TinyZzh** [comment]
[#17 ] 在查看DEMO的进度
